#!/bin/sh
#
# Nginx configuration manager
#
## Version: 2019-01-23
## Copyright (C) 2019 Jakub Arbet <jakub.arbet@protonmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

TEMPLATE_PATH=$(pwd)/templates

usage() {
    echo "$0 usage:" && grep "[[:space:]])\ #" $0 | sed 's/#//' | sed -r 's/\) /-/';
}

version() {
    sed -n "/sed/d;s/## //gp" $0
}

type=default

while getopts ":hvt:" opt; do
  case ${opt} in
    t ) # type of virtual host
        type=${OPTARG}
        ;;
    v ) # output version information and exit
        version
        exit 0
        ;;
    h ) # display this help and exit
        usage
        ;;
   esac
done

template=${TEMPLATE_PATH}/${type}.conf

if [[ ! -e $template ]]; then
    echo "Invalid type specified"
    exit 1
fi



exit 1
